spring:
  application:
    name: aatranscript-opeinai-app
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

  output:
    ansi:
      enabled: always
  doc:
    swagger-ui:
      path: /docs

sfg:
  aiapp:
    vectorStorePath: vectorstore_tri.json
    documentsToLoad: classpath:/movies500Trimmed.csv