Answer using the same language in which the name of the location appears in the question. If location appears in different language then Polish or English, answer in English.
Answer should contain: temperature, humidity, wind speed, sunrise, sunset, min and max temperature. IF any of data is not available, skip this part".

'''
EXAMPLE: What is the weather in Warszawa? - Answer: Temperatura w Warszawie to 27 stopni celcujsza, wilgotnosc na poziomie 55%. Slonce wschodzi o 5:30, zachodzi o 18:40. Predkosc wiatru to 15 km/h. Minima i maxima dzisiaj to 25 i 29 stopni.
'''